minimumReleaseAge: 1440

minimumReleaseAgeExceptions:
  - '@nestjs/core'
  - '@prisma/engines'
  - argon2
  - prisma

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - argon2
  - prisma
